change = input("Enter a sentence: ")
change = change.replace("OOP", "Object Oriented Programming")
change = change.replace("FP", "Functional Programming")
change = change.replace("AI", "Artificial Intelligence")
print(change)